---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Version History

## 0.2.0.9000 2023-1028

* Updated refresh for testing
* Added qmod and qplot options to setup

## 0.2.0 2023-1020

* Removed deprecated qconfig functions
* Removed set_colnames to re-export
* Updated archive to default to exclude data directory, unless option evoked
* Updates to all tests for testthat v3
* Updates to improve devtools::check

## 0.1.11 2023-0625

* Added get_dates to find typical date values from Qualtrics data files
* Added response_calendar to visualize what which dates have records associated with them based on typical date values from Qualtrics data files
* Added a convenience version function

## 0.1.10 2023-0201

* Bug fixes related to updates to dplyr 1.1.0 and tidyr 1.3.0

## 0.1.9 2023-0123

* Updated set_up to work properly even if qkey details fail to import properly and to execute correctly if existing project launched by Rproj file in another location
* Updated fix_na to include a median replace option and removed a potentially faulty error check
* Updated describe to round output for improved readability, added round parameter so user can control as needed
* Updated pull_labels to use supplied metadata due to Qualtrics API changes
* Updated create_frequencies to use supplied metadata due to Qualtrics API changes and added separate progress bars for generating frequencies and for exporting to Excel
* Updated create_codebook to use supplied metadata due to Qualtrics API changes

* Added create_na to easily replace values, like -99 or "blanks" with NA instead
* Added nps_score convenience function to easy calculate NPS score for LTR data
* Added qcor_plot to generate corrplots with some reasonable visual settings
* Added week_number convenience function to easy calculate a week number from date data

## 0.1.8 2022-0701

* Deprecating qconfig in place of qkey family of functions

## 0.1.7 - 2022-0518

* Updated create_dictionary to correctly show frequencies with numeric data
* Updated tests for create_dictionary, create_frequencies, create_qconfig to correctly reset or pass during testing
* Updated pull_labels to account for name problem if variable named value

## 0.1.6 - 2202-0423

* Updated dependencies to correct install problem

## 0.1.5 - 2022-0422

* Removed data type issued for create_codebook that would sometimes cause an error
* Added a progress bar and beepr:beep to create_frequencies
* Added create_dictionary

## 0.1.4 - 2022-0314

* Added filters to archive_project to remove .tmp and .qconfig files

## 0.1.3 - 2022-02-08

* Added create_frequencies and separated function from create_codebook
* Cleaned up NEWS and README


## 0.1.2 - 2022-02-03

* Added additional quartiles to the describe function

## 0.1.1 - 2022-02-01

* Added the following functions:

  + create_codebook
  + create_qconfig, view_qconfig, delete_qconfig
  + describe
  + flip
  + pull_labels
  + refresh
  
## 0.1.0 - 2021-09-12

* Initial release, including the following functions:

  + archive_project, delete_project
  + clean_names
  + create_id
  + fix_na
  + freq, crosstab, threeway
  + rescale
  + set_colnames
  + set_up
  + topbox, botbox
  + write_xlsx


